version: '3.3'
services:
  cache:
    image: redis:7.0-rc-bullseye
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PWD}
    volumes: 
      - cache:/data
volumes:
  cache:
    driver: local